### ISSUE TITLE
Skillport Updated

### ISSUE THREAD

**Issue by bjornmikeljacobson** [Clutch152/scripts#17]

**Comment by uplusion23** [comment]
The script on here isn't updated but I've made my own. Only do about one entire course a day, since I haven't emulated the time spent yet, but here you go.

```/*
    README:
    
    1. Open the desired course. Use F12 (Developer Options) and go to the "Console" tab.
    
    2. Paste the script into the console, and press ENTER or hit the green arrow.
    
    3. Once the page closes (it will exit automatically) launch the partially completed course, and repeat steps 1 and 2.
 
    4. Once the course is closed again, it should be completed.

    5. Submit me for an ARCOM.
*/

var w = Core.context.getResultsMgr().masterBucket.topicStatusItems.elements();
var g = Core.context.course.getLessonIDs();
if (g != null) {
  var k = g.length;
  for (var f = 0; f < k; f++) {
    var m = g[f];
    var c = Core.context.course.getTopicIDsForLesson(m);
    if (c != null) {
      var e = c.length;
      for (var d = 0; d < e; d++) {
        var a = c[d];
        Core.context.getResultsMgr().setTVS(a, Core.GenericConstants.C);
      }
    }
  }
}

var r = 0;
while(w.hasMoreElements()) {
  while (r < 70 || r > 100) {
    r = Math.floor((Math.random() * 100));
  }
  var x = w.nextElement();
  if (x.numberOfObjectives > 0) {
    x.setScore(r, false);
    r = 0;
  }
}

top.close();```

**Comment by bjornmikeljacobson** [comment]
Bro,

You're the best. Send me your cashapp and I'll shoot you $20 on the 1st for
your efforts. I know its worth more, but you know how much we make so
that's what I got.

**Comment by ExoticMidnight** [comment]
Bad ass what class is it for?

**Comment by uplusion23** [comment]
Should work on most.

**Comment by AcuraTL** [comment]
Do I combine it with the old one, or by itself, or what do I paste bc i get a "Uncaught SyntaxError: Unexpected token *" error when I paste this new one by itself into the console. thank you

**Comment by 85red255** [comment]
doesnt work

**Comment by uplusion23** [comment]
Should work now. GitHub formatting broke it.

**Comment by Fullerpj** [comment]
Uplusion23 is there anyway that you can produce a new one? The current one you redid is no longer working

**Comment by ExoticMidnight** [comment]
I’m also trying to get one my skillport log in isn’t working at the moment

**Comment by Fullerpj** [comment]
*ping*

**Comment by ExoticMidnight** [comment]
???

**Comment by Fullerpj** [comment]
I dont think Uplusion23 is around to fix it

**Comment by iEatNoodlez** [comment]
> 
> 
> _ping_

pong, will look into it

**Comment by Clutch152** [comment]
I posted a fix not too long ago. Hopefully it still works. All code is now open to contributions by way of pull request.

**Comment by Adr254** [comment]
Is there a new code that's updated ? really need the points

**Comment by Forbeswishlis** [comment]
Can someone send me the updated script 
Marcusforbes43@gmail.com

**Comment by iEatNoodlez** [comment]
This discussion has been closed due to the upgrade of percipio.
