### ISSUE TITLE
SkillPort Script  Stopped Working...

### ISSUE THREAD

**Issue by jeremyt018** [Clutch152/scripts#21]
The script Skillport_breaker.js stopped working a few hours ago. (While using Internet Explorer) When it comes to the test and you place the code, now it says the following error... 

Unable to get property ' elements ' of undefined or null reference.

In addition when also attempting in Crome I get this error.

Uncaught  TypeError: Cannot read properly 'elements' of undefined at <annonymous>:3:64

VM355:3

**Comment by Ishking** [comment]
> The script Skillport_breaker.js stopped working a few hours ago. (While using Internet Explorer) When it comes to the test and you place the code, now it says the following error...
> 
> Unable to get property ' elements ' of undefined or null reference.
> 
> In addition when also attempting in Crome I get this error.
> 
> Uncaught TypeError: Cannot read properly 'elements' of undefined at :3:64
> 
> VM355:3

Any update on this ?

**Comment by iEatNoodlez** [comment]
This discussion has been closed due to the upgrade of percipio.
