### ISSUE TITLE
SSD 1

### ISSUE THREAD

**Issue by WyvernDuckie** [Clutch152/scripts#3]
Every time I launch SSD 1 and inject the script into the module I get a 'scorm_api' is undefined error. Is there a fix to this?

**Comment by iEatNoodlez** [comment]
http://www.noodlez.org/paste/paste.php?id=3

Updated for you. Enjoy

**Comment by Diablito** [comment]
iEatNoodlez code is saying "'sco' is undefined" and how exactly do you target the  frameset?

**Comment by iEatNoodlez** [comment]
@Diablito you need to look at the top left of the console.

**Comment by Diablito** [comment]
@iEatNoodlez i found the select element but where is the frame set? its not showing up with CTRL+F, also it still say SCO is undefined

**Comment by iEatNoodlez** [comment]
@Diablito Sorry for the late reply. Below you will find out what I'm talking about. 

<img width="529" alt="example" src="https://user-images.githubusercontent.com/1365579/38168188-e2dd125e-34f1-11e8-95c8-d137b8f18289.PNG">

**Comment by Diablito** [comment]
@iEatNoodlez ill give it another go, and what exactly do you do is the SCO is undefined? and is there anywhere else i can contact you?

**Comment by iEatNoodlez** [comment]
@Diablito Feel free to use Discord or email
Discord Noodlez#0001
Email me@noodlez.org

**Comment by Diablito** [comment]
@iEatNoodlez just sent the request on discord, i appreciate it.

**Comment by dashboardabc** [comment]
idk bout all that but after testing a bunch i found this code and this works for me instantly for lessons. and a lot simpler.
Just load up lesson as usual open console f12, just paste

SetLesson_Status("completed");

and exit. works instantly and like once it didnt update so i just did it again and completes the lesson.
For the tests i just follow noodlez method

finished the whole thing in like 20 min

**Comment by rcbdakota** [comment]
Noodlez test method isn't working for me. it says 'SCORIMAP' is unidentified

**Comment by rcbdakota** [comment]
The portion for the tests aren't working for me.



Thank you,

Dakotajames E. Crawfoot
Phone: (346) 300-7676
E-mail: rcbdakota@gmail.com
Work hours: 9:00am-5:00pm  M-F Hawaii Time

**Comment by klawls** [comment]
Can somebody please tell me how to get to the navigation page and then open document 11 in console?

**Comment by GregAllen95** [comment]
Do these still work? I'm using IE11 and when I go to console there is no textbox to enject code.

**Comment by lToris** [comment]
Isnt working anymore in the test portion the system doesnt let you press F12 or do a right click

**Comment by GregAllen95** [comment]
@IToris I just used the scripts two weeks ago and they worked. When the test window pops up you have to immediately right click it and hit "Inspect Element" and that will bring up the console. If you take too long you won't be able too.

**Comment by lToris** [comment]
Tanks im about to go to the library and try to do it

**Comment by wulfiebard** [comment]
To the people having the scorm issues, TAKE OFF COMPATIBILITY VIEW. then you can select the correct target and input noodlez. youll have to call the helpdesk for them to verify the passing score but its still faster than trial and error.-bard verified working 12-30-18

**Comment by wulfiebard** [comment]
> SetLesson_Status("completed");

add top.close(); to the end i.e------     SetLesson_Status("completed");top.close();    ------------extra step towards true laziness

**Comment by therikoxide** [comment]
I think they killed the Noodlez code.  Returns "Expected ';' " when it is entered.

**Comment by wulfiebard** [comment]
Worked for me 2 days ago, what module?

**Comment by therikoxide** [comment]
SSDI Mod3 Module 3 Introduction and SSDI Mod3 Casualty Assistance

I enabled compatability > loaded the module > waited until the content popup loaded, when back to the check mark popup > opened the console > set it to 11 > then set it to the correct .js target > then ran the script (both line by line and as a whole). Same error every time. 

Tried loading it without compatability mode and the module won't load. Also appended your top.close, but received the same error. :/

**Comment by wulfiebard** [comment]
Click over to issues click ssd1 scroll to the bottom you'll see my code

**Comment by wulfiebard** [comment]
Nvm reread your msg, put back in compatibility mode refresh alms go back
into module don't worry about the 11 keep on 7 and enter my code

**Comment by wulfiebard** [comment]
dont worry about clicking over to jps just f12 it and paste-> play button

**Comment by therikoxide** [comment]
Thanks! Not sure what was causing it earlier, but good to go after following your last two instructions.

**Comment by wulfiebard** [comment]
no problem, when you get to module 4 last one called map reading use the main script code not mine or noodlez, only one that works

**Comment by wulfiebard** [comment]
for the module exams use noodlez test method to the T, it won't immediately display completed

**Comment by Apocro** [comment]
going to post this here since it is still semi-active.

~~~~
Trying to do the Exams in SSD3

I click Launch, wait for the navigation to load, i inspect element and get SCOSetValue is undefined
I try the code in the Navigation window and get Object doesn't support property or method

I can't target cp3engine as seen here http://www.noodlez.org/paste/paste.php?id=3

Please... any advice

**Comment by wulfiebard** [comment]
Does top right of console say 11? Little screen

**Comment by Apocro** [comment]
Yes,

I've tried document mode emulation 7,8,9,10,11 (7 and 8 fail to load correctly)

**Comment by Apocro** [comment]
I got it working using a mash of SSD2 code;

Just press F12 once the test page loads, go into console, paste this and submit.

	score=0;
	while(score < 80 || score > 100){
		score=Math.floor(Math.random()*1000)
	}
	cwsObj.getCourseCompleted=function(){return true};
	cwsObj.user.courseScore=score;
	cwsObj.session.finished();

**Comment by wulfiebard** [comment]
Registered as complete? If so add it to ssd3 code, and which code worked
under lessons?

**Comment by Apocro** [comment]
Yup works great! I'll add it.

I didn't use any code for the actual lessons

**Comment by arcticsoldier** [comment]
So currently trying to complete SSD 1 when doing the lessons im pasting a mix of

**Comment by arcticsoldier** [comment]
When you guys were doing the Exams was the f12 function disabled

**Comment by wulfiebard** [comment]
tricky trick on that one, as soon as you click onto the exam itll pop up a
box and then another box for the quiz itself, you have to quickly right
click on the exam box (anywhere) and click "inspect element", if you dont
do it fast enough just exit the exam and retry til it works. Good luck

**Comment by wulfiebard** [comment]
also for the lessons use this code SetLesson_Status("completed");top.close();

**Comment by arcticsoldier** [comment]
Damn its fast as hell, I mean the second it pops up I try and rick click and it grants me with a prompt " Use of right click function is prohibited during this exam"

**Comment by wulfiebard** [comment]
yeah it is, best to use shitty wifi for it, also when you try the codes for lessons do you have compatibility view off or on?

**Comment by arcticsoldier** [comment]
With the lessons i had to tinker with turning compatibility mode on and off and then switch to console version 5 using SetLesson_Status("completed");top.close() this string of text

**Comment by wulfiebard** [comment]
noodlez method (top section for link) works great for exams just gotta follow it to the letter, keep trying on timing the click, try using a free vpn to slow down your speed some

**Comment by arcticsoldier** [comment]
Any specific VPN you recommend for me to use to try and slow it down a little?

**Comment by wulfiebard** [comment]
i personally use betternet vpn, free and relatively slower

**Comment by WaffleBottoms** [comment]
So I might just be stupid, but I keep getting SCO undefined. Also do i have to target frameset, and if so how do I do that.

**Comment by wulfiebard** [comment]
read noodles method, top right looks like a little screen

**Comment by seang1121** [comment]
so noodlez.org isnt working i click it and get directed to hostwinds does anyone have the script/code from there for the tests????

**Comment by wulfiebard** [comment]
compatibility view off, switch little monitor thing in top right to 11 from
7, refresh, quickly right click and inspect element as soon as test page
pops up because you cant function key it.

SCORMAPI.dataModelInterface.root.containers.cmi.elements.scaled_passing_score.writeable=true;
SCORMAPI.SetValue("cmi.scaled_passing_score", 0.8);
SCORMAPI.SetValue("cmi.score.scaled", 0.9);
SCORMAPI.SetValue("cmi.completion_status", "completed");
SCORMAPI.SetValue("cmi.success_status", "passed");
SCORMAPI.SetValue("cmi.score.raw", 90);
SCORMAPI.SetValue("adl.nav.request", "continue");

SCORMAPI.Commit();
SCORMAPI.FrameworkTerminate();
SCORMAPI.completeUserSession(true);

**Comment by jamicushouse** [comment]
Scormapi undifined

**Comment by jamicushouse** [comment]
Even with changing it to 7 it doesn't work any ideas?

**Comment by iEatNoodlez** [comment]
Since this is still an active thread and all, I haven't been able to look for other work arounds mainly because there isn't a way to repopulate SSD1 in ALMS. I would usually wait til a new private came in, but being a specific series where at AIT it's required to do it as a phase up and being in a remote location where privates dont come everyday it was kind of hard, then I would have to go through the hastle of sitting in IE's Dev tools for about 20 minutes. But I brought the news of I just PCS'd to Fort Hood if anyone want's to give it a go that's local. But as always I couldn't guarantee that there wouldn't be a flag on your account after it.

**Comment by iEatNoodlez** [comment]
Also, just a forwarning, there has been people that there whole lesson would be bricked because of the fact that the course content want's to mark the TOC as complete but the TOC already says complete. Just letting you know. For this you will have to call ALMS helpdesk and have them completely disenroll you from the course and reenroll you.

**Comment by lToris** [comment]
SSD 1 is not longer supported, we need to do DLC 1 and if you are enrolled
to SSD1 you have until Sep 30 2019 to complet it and get full credit for it.

Also if you arent a Spc you are not elegible to be enrolled in DLC 1
something that you have to do thru your chain of comand

**Comment by Juicy5** [comment]
I have got through all the lessons with this code, SetLesson_Status("completed");top.close(); .
It doesn't work on the last lesson, SSDI Mod4 Map Reading. I also tried noodlez code as well as different document modes and switching compatibility mode. Does anyone have a solution for this.

**Comment by IBANDITOI** [comment]
STILL WORKING AS OF LATE AUGUST 2019 CODE WILL NOT WORK FOR SSD1 Mod4 MAP READING WILL WORK FOR EVERYTHING ELSE INCLUDING TESTS JUST REOPEN THE QUIZ AND CLICK THROUGH THE TESTS AFTER FOLLOWING THE STEPS

**Comment by Clutch152** [comment]
Please submit a pull request with a complete fix and I will merge it so it can be updated :)

**Comment by Hectoronian** [comment]
I guess we can close this or modify the name for the newer DLC's?

Best regards!!
