### ISSUE TITLE
Dlc 2 working code (clutch post it please)

### ISSUE THREAD

**Issue by wulfiebard** [Clutch152/scripts#45]
opener.scorm.set("cmi.completion_status","completed");
opener.scorm.set("cmi.success_status","passed")
window.close();

**Comment by alexreyne** [comment]
If you're saying this works, you can fork the repo and then submit a pull request for him to merge it. I can do it for you if you'd like.

**Comment by wulfiebard** [comment]
@alexreyne got it thanks. I just glanced earlier when I got it working so quick posted

**Comment by real-human-person** [comment]
Can I ask how you ended up figuring this out? Did you have prior knowledge of Scorm?

I ended up finding a reference PDF for Scorm, here:

http://ivory-zebra-409f9b960cb1d313.znlc.jp/aen/content/act2005eg/data/txt2.pdf

and I can see how you would have gotten there eventually, but did you go about it another way?

Super helpful, btw.

**Comment by iEatNoodlez** [comment]
@real-human-person SCORM is an old LMS framework. You can find documentation on it everywhere. There is also some hard coded calls on course completion. ALMS is slowly phasing out SCORM or passing in additional parameters for checking for course completion and cheating.
