### ISSUE TITLE
Script Issues

### ISSUE THREAD

**Issue by TheRealGloxk** [Clutch152/scripts#62]
So I'm having issues getting the script to work I've seen the one by @TyrantRex was recently updated. However, It's not working for me...  I had it working previously.. but user error??

**Comment by TyrantRex** [comment]
Nah, the back end team from skillsoft was fairly active and managed to patch the script. They've also implemented countermeasures and are actively deactivating accounts so I wouldn't recommend it.

**Comment by TheRealGloxk** [comment]
@TyrantRex Any recommended amount of hours for completion? Not sure how much you actually know. I'm close and just need to get some out the way.

**Comment by TyrantRex** [comment]
@TheRealGloxk Daily, I’d recommend doing an amount that’s feasible or sensible within 24 hours. In total, you’d want to see 400 if you’re going for stripes, 600 if you’re going for 6. It’s 5h per point

**Comment by Tonypdl94** [comment]
Can someone send me a working script pls? Tonyp192@gmail.com

**Comment by iEatNoodlez** [comment]
This discussion has been closed due to the upgrade of percipio.
