### ISSUE TITLE
Mitmproxy update

### ISSUE THREAD

**Issue by GotEmCoach** [Clutch152/scripts#66]
On a seperate private project i've begun automating interception of packets via python and modifying content automatically and seeing as I have time this summer, I am going to update the mitmproxy instructions that include the specialized vimrc files and moving the execution of python from mitmproxy using vim to just using mitmproxy's ability to create functions to change packets on the fly. 

The new command should be as simple as running mitmproxy -s skillport_script.py, all the user will have to do is navigate through the course aka open and click close. It's pretty easy to catch packets that the underlying javascript is going to send to the server after they are done obfuscating how they come up with the packet to send and edit it that way. 

More to come soon.

**Comment by GotEmCoach** [comment]
I have a pull request in can one of the maintainers take a look and close this out.

**Comment by iEatNoodlez** [comment]
Will validate soon.

**Comment by iEatNoodlez** [comment]
Merged.
