### ISSUE TITLE
URGENT PLEASE READ

### ISSUE THREAD

**Issue by the-mighty-fall** [Clutch152/scripts#7]
+JKO IS NOW DISABLING ACCOUNTS THAT ARE CAUGHT BYPASSING COURSES SHOULDN'T BE A ISSUE WITH DOING 1 OR 2 COURSES 
+ANYTHING OTHER THEN THAT SEEMS TO BE CAUSING A TRIGGER WITH THE TIME SPENT ON THE COURSE
+CURRENTLY TRYING TO INPUT THE TIME IN THE API, STILL TESTING IT
+BUT FOR NOW USE AT YOUR OWN RISK.

**Comment by iEatNoodlez** [comment]
@the-mighty-fall Are you sure it's timing? Didn't really want to wait around 30 minutes to find out.

**Comment by the-mighty-fall** [comment]
Postive, saw screenshot of a jko admin email that they sent a user saying that he completed a 80hr course in 5 mins so they disabled his account, I just did 180, modifying the time im going to wait a day  to see what happens

**Comment by iEatNoodlez** [comment]
@the-mighty-fall Still waiting on positive confirmation.

**Comment by the-mighty-fall** [comment]
No ban with 160 hours, with the time changed, ill try 300 next

**Comment by betamax2021** [comment]
Hoping this gets fixed

**Comment by betamax2021** [comment]
I have found that if you use something like autohotkey (Automator in my case OSX) and paste the script, enter, then wait two+ minutes you don’t get that warning. Then for the tests only paste the command before the “if” statement then close the tab. When you reopen the course, click resume the test will be done and no error will bug you. I have the whole thing done with Automator so I just sign in before I go to bed and the course is complete by the morning.

**Comment by the-mighty-fall** [comment]
javascript:(function(){console.log(API.LMSInitialize(""),API.LMSSetValue("cmi.core.lesson_status","completed"), API.LMSSetValue("cmi.objectives.n.status","completed"), API.LMSSetValue("cmi.success_status","completed"),API.LMSSetValue("cmi.core.session_time","0000:19:16.73"),API.LMSSetValue("cmi.interactions.3.time","01:23:58"),API.LMSFinish(""));})();


this is what is what i have been using for some courses, the time value i add to pretty much everything on jko and haven't been restricted yet, ets'd recently so ill be releasing some stuff

**Comment by zebu16** [comment]
Still not able to use this could you elaborate

**Comment by the-mighty-fall** [comment]
> Still not able to use this could you elaborate

Add all of that that i posted to a bookmark on the bookmark bar, its easy just copy and paste it where the url would go, once you get to the course click on the bookmark

**Comment by zachm611** [comment]
Is there another script with time in it? I triedjavascript:(function(){console.log(API.LMSInitialize(""),API.LMSSetValue("cmi.core.lesson_status","completed"), API.LMSSetValue("cmi.objectives.n.status","completed"), API.LMSSetValue("cmi.success_status","completed"),API.LMSSetValue("cmi.core.session_time","0000:19:16.73"),API.LMSSetValue("cmi.interactions.3.time","01:23:58"),API.LMSFinish(""));})();  but it did not work.  Thanks!

**Comment by DLJONES96** [comment]
Any updates on this?
