### ISSUE TITLE
skillport_breaker.user.js

### ISSUE THREAD

**Issue by litoski306** [Clutch152/scripts#74]
skillport_breaker.user.js has stopped working for around 10 days if someone has a working code can you direct message me or send me your email

**Comment by doorbelldeadpool** [comment]
Same here 

Skillport is about to switch over Jan 3

**Comment by coobyjohnson** [comment]
the MITM and .js scripts are both no longer working.

**Comment by keengkobr** [comment]
> the MITM and .js scripts are both no longer working.

Follow up, .js script is broken but MITM is working as intended. I didn't call the right var in filesystem. pebcac :)

**Comment by afrika509** [comment]
I'm stuck on the MITM

Step 1: You will now run the following:
    `python3 mitmproxy -s skillport_mitmproxy.py`
    
   I've tried saving the .py to /opt/homebrew/bin/ to run but no dice. What am I doing wrong?

**Comment by keengkobr** [comment]
> I'm stuck on the MITM
> 
> Step 1: You will now run the following: `python3 mitmproxy -s skillport_mitmproxy.py`
> 
> I've tried saving the .py to /opt/homebrew/bin/ to run but no dice. What am I doing wrong?

https://stackoverflow.com/questions/58884452/usr-local-bin-mitmproxy-no-such-script

**Comment by afrika509** [comment]
Thank you, I’ll try it tomorrow and let you know how it goes

**Comment by afrika509** [comment]
@keengkobr works perfectly, I was trying to do it from macOS and was giving me problems, did it on Linux and worked like a charm

**Comment by doorbelldeadpool** [comment]
Can anyone explain what your using

**Comment by afrika509** [comment]
I’m using the latest Kali Linux and Firefox for my browser proxy. Once skillport_mitmproxy.py is in /usr/bin/ run python3 mitmproxy -s skillport_mitmproxy.py

**Comment by Ormethious** [comment]
@afrika509 Think you got time to hop on discord sometime and help me out with linux??

**Comment by afrika509** [comment]
Yes no problem afrika509#7928 on discord

**Comment by ExoticMidnight** [comment]
Can I add you also? I’d like to use linux with all the army classes as wellSent from unknown locationOn Dec 5, 2022, at 21:18, afrika509 ***@***.***> wrote:﻿
Yes no problem afrika509#7928 on discord

**Comment by afrika509** [comment]
Yes go ahead

**Comment by Ormethious** [comment]
@afrika509 Sent a friend request, its russian letters.

**Comment by ExoticMidnight** [comment]
Sent came from ChifladoOn Dec 5, 2022, at 21:18, afrika509 ***@***.***> wrote:﻿
Yes no problem afrika509#7928 on discord

**Comment by iEatNoodlez** [comment]
This discussion has been closed due to the upgrade of percipio.
