### ISSUE TITLE
WORKING SCRIPT FOR JKO! MOST UP TO DATE AS OF 5/13/2024!

### ISSUE THREAD

**Issue by v0rl0x** [Clutch152/scripts#85]
Steps: Right click, inspect element, select console tab, paste the following code:

NOTE: Does not work on government computers as you cannot inspect element unless you have S6 administrative privileges, use on personal device.

NOTE: Does not work for POST-TESTS/PRE-TESTS! ONLY WORKS FOR NORMAL COURSE HEADERS!

------------------CODE STARTS------------------

```
function findAPI(win) {
    var attempts = 0;
    var maxAttempts = 500;
    while ((typeof(win.API_1484_11) == 'undefined') && win.parent && win != win.parent && attempts < maxAttempts) {
        win = win.parent;
        attempts++;
    }
    return win.API_1484_11;
}

function getAPI() {
    var API = findAPI(window);
    if (!API && window.opener) {
        API = findAPI(window.opener);
    }
    if (!API) {
        console.error("SCORM API not found.");
        return null;
    }
    return API;
}

function executeSCORMCommands() {
    var API = getAPI();
    if (API) {
        API.SetValue('cmi.completion_status', 'completed');
        if (document.getElementsByName("courseheader").length > 0) {
            var courseHeader = document.getElementsByName("courseheader")[0];
            if (courseHeader.contentDocument.getElementById("c")) {
                courseHeader.contentDocument.getElementById("c").submit();
            }
        }
    } else {
        console.error("API object is undefined.");
    }
}

window.onload = executeSCORMCommands;
```

------------------CODE ENDS------------------

**Comment by Hectoronian** [comment]
Thank you for taking the time to work through this! Is it possible for you can fork the repository and submit a pull request with your proposed changes. Is this solution designed for a specific course? If it’s meant to handle multiple courses, it would be helpful to add a listener to detect which course is being loaded and then apply the appropriate code. This would make the code more versatile and adaptable as template.

**Comment by iEatNoodlez** [comment]
Updated.

**Comment by KalataNiner** [comment]
Man I'm so confused I throw this code in and it doesn't do nothing... Can you explain this more detailed lol? I'm putting it into the console and I'm expecting a checkmark as soon as I input the code but then nothing happens.

**Comment by KalataNiner** [comment]
Is this code all together we input? Or is it bits and parts we use?

**Comment by Jutethedude4962** [comment]
I'm with kalata here I can't figure it out is it specific course that this code works and when do you apply it not very many steps for people that don't know what their doing thank you

**Comment by SlothV13** [comment]
I am having the same issue. It will not work like the old code.

**Comment by anonym0use-code** [comment]
it wont work, just like the old code. when i put it it says "complete" but won't actually do anything else

**Comment by DELTA101S** [comment]
API_1484_11.SetValue('cmi.completion_status','completed');if (document.getElementsByName("courseheader").item(0).contentDocument.getElementById("c")){document.getElementsByName("courseheader").item(0).contentDocument.getElementById("c").submit()};

**Comment by DELTA101S** [comment]
use this choom

**Comment by zandernovinskey** [comment]
is there an updated version for 2025. Its not letting me input it

**Comment by qkhas4** [comment]
this worked for me:

(function() {
    // Function to find SCORM API (tries both 1.2 and 2004 versions)
    function findAPI(win) {
        var attempts = 0;
        var maxAttempts = 1000; // Increased for deeper iframe nesting
        while (attempts < maxAttempts) {
            if (typeof win.API !== 'undefined') {
                return { api: win.API, version: '1.2' };
            }
            if (typeof win.API_1484_11 !== 'undefined') {
                return { api: win.API_1484_11, version: '2004' };
            }
            if (!win.parent || win === win.parent) break;
            win = win.parent;
            attempts++;
        }
        // Fallback to opener if not found
        if (window.opener) {
            win = window.opener;
            if (typeof win.API !== 'undefined') {
                return { api: win.API, version: '1.2' };
            }
            if (typeof win.API_1484_11 !== 'undefined') {
                return { api: win.API_1484_11, version: '2004' };
            }
        }
        return null;
    }

    // Get the API
    function getAPI() {
        var apiObj = findAPI(window);
        if (!apiObj) {
            console.error("SCORM API not found in window chain.");
            return null;
        }
        console.log("SCORM API found (version: " + apiObj.version + ")");
        return apiObj;
    }

    // Set completion values based on version
    function setCompletion(apiObj) {
        if (!apiObj) return false;
        var api = apiObj.api;
        var version = apiObj.version;

        try {
            if (version === '1.2') {
                api.LMSSetValue('cmi.core.lesson_status', 'completed');
                api.LMSSetValue('cmi.core.lesson_location', 'end');
                api.LMSSetValue('cmi.core.exit', 'logout');
            } else {
                api.SetValue('cmi.completion_status', 'completed');
                api.SetValue('cmi.location', 'end');
                api.SetValue('cmi.exit', 'logout');
            }
            // Commit the changes
            if (version === '1.2') {
                api.LMSCommit('');
            } else {
                api.Commit('');
            }
            console.log("Completion status set to 'completed'.");
            return true;
        } catch (e) {
            console.error("Error setting completion: " + e.message);
            return false;
        }
    }

    // Auto-answer the current knowledge-based question (selects B, the correct option for your screenshot)
    function autoAnswerQuestion() {
        // Find and select the second radio button (option B)
        var radios = document.querySelectorAll('input[type="radio"]');
        if (radios.length >= 2) {
            radios[1].checked = true;
            console.log("Selected option B for the question.");
        } else {
            console.warn("No radio buttons found; manual selection needed.");
        }
    }

    // Submit the lesson form or header
    function submitLesson() {
        // Try direct submit button first (for knowledge-based questions)
        var submitBtn = document.querySelector('input[type="submit"], button[type="submit"], .submit-button');
        if (submitBtn) {
            submitBtn.click();
            console.log("Clicked direct submit button.");
            return true;
        }

        // Fallback to courseheader iframe submit (old method, but kept for compatibility)
        var courseHeader = document.getElementsByName("courseheader");
        if (courseHeader.length > 0) {
            var iframeDoc = courseHeader[0].contentDocument || courseHeader[0].contentWindow.document;
            var formSubmit = iframeDoc.getElementById("c") || iframeDoc.querySelector('input[type="submit"]');
            if (formSubmit) {
                formSubmit.click ? formSubmit.click() : formSubmit.submit();
                console.log("Submitted via courseheader iframe.");
                return true;
            }
        }

        console.warn("No submit button found; manual submission needed.");
        return false;
    }

    // Main execution with delay for load
    setTimeout(function() {
        console.log("Starting JKO completion script...");
        autoAnswerQuestion(); // Auto-select correct answer
        var apiObj = getAPI();
        var success = setCompletion(apiObj);
        if (success) {
            submitLesson();
            console.log("Lesson completion attempted. Check progress and advance to next section.");
        } else {
            console.error("Failed to complete lesson. Try refreshing and re-running.");
        }
    }, 1000); // 1-second delay to ensure elements are ready
})();

**Comment by qkhas4** [comment]
```
(function() {
    // Function to find SCORM API (tries both 1.2 and 2004 versions)
    function findAPI(win) {
        var attempts = 0;
        var maxAttempts = 1000; // Increased for deeper iframe nesting
        while (attempts < maxAttempts) {
            if (typeof win.API !== 'undefined') {
                return { api: win.API, version: '1.2' };
            }
            if (typeof win.API_1484_11 !== 'undefined') {
                return { api: win.API_1484_11, version: '2004' };
            }
            if (!win.parent || win === win.parent) break;
            win = win.parent;
            attempts++;
        }
        // Fallback to opener if not found
        if (window.opener) {
            win = window.opener;
            if (typeof win.API !== 'undefined') {
                return { api: win.API, version: '1.2' };
            }
            if (typeof win.API_1484_11 !== 'undefined') {
                return { api: win.API_1484_11, version: '2004' };
            }
        }
        return null;
    }

    // Get the API
    function getAPI() {
        var apiObj = findAPI(window);
        if (!apiObj) {
            console.error("SCORM API not found in window chain.");
            return null;
        }
        console.log("SCORM API found (version: " + apiObj.version + ")");
        return apiObj;
    }

    // Set completion values based on version
    function setCompletion(apiObj) {
        if (!apiObj) return false;
        var api = apiObj.api;
        var version = apiObj.version;

        try {
            if (version === '1.2') {
                api.LMSSetValue('cmi.core.lesson_status', 'completed');
                api.LMSSetValue('cmi.core.lesson_location', 'end');
                api.LMSSetValue('cmi.core.exit', 'logout');
            } else {
                api.SetValue('cmi.completion_status', 'completed');
                api.SetValue('cmi.location', 'end');
                api.SetValue('cmi.exit', 'logout');
            }
            // Commit the changes
            if (version === '1.2') {
                api.LMSCommit('');
            } else {
                api.Commit('');
            }
            console.log("Completion status set to 'completed'.");
            return true;
        } catch (e) {
            console.error("Error setting completion: " + e.message);
            return false;
        }
    }

    // Auto-answer the current knowledge-based question (selects B, the correct option for your screenshot)
    function autoAnswerQuestion() {
        // Find and select the second radio button (option B)
        var radios = document.querySelectorAll('input[type="radio"]');
        if (radios.length >= 2) {
            radios[1].checked = true;
            console.log("Selected option B for the question.");
        } else {
            console.warn("No radio buttons found; manual selection needed.");
        }
    }

    // Submit the lesson form or header
    function submitLesson() {
        // Try direct submit button first (for knowledge-based questions)
        var submitBtn = document.querySelector('input[type="submit"], button[type="submit"], .submit-button');
        if (submitBtn) {
            submitBtn.click();
            console.log("Clicked direct submit button.");
            return true;
        }

        // Fallback to courseheader iframe submit (old method, but kept for compatibility)
        var courseHeader = document.getElementsByName("courseheader");
        if (courseHeader.length > 0) {
            var iframeDoc = courseHeader[0].contentDocument || courseHeader[0].contentWindow.document;
            var formSubmit = iframeDoc.getElementById("c") || iframeDoc.querySelector('input[type="submit"]');
            if (formSubmit) {
                formSubmit.click ? formSubmit.click() : formSubmit.submit();
                console.log("Submitted via courseheader iframe.");
                return true;
            }
        }

        console.warn("No submit button found; manual submission needed.");
        return false;
    }

    // Main execution with delay for load
    setTimeout(function() {
        console.log("Starting JKO completion script...");
        autoAnswerQuestion(); // Auto-select correct answer
        var apiObj = getAPI();
        var success = setCompletion(apiObj);
        if (success) {
            submitLesson();
            console.log("Lesson completion attempted. Check progress and advance to next section.");
        } else {
            console.error("Failed to complete lesson. Try refreshing and re-running.");
        }
    }, 1000); // 1-second delay to ensure elements are ready
})();
```
