### ISSUE TITLE
Codes for ATIS learning

### ISSUE THREAD

**Issue by SecretJsal** [Clutch152/scripts#88]
Are there any codes for ATIS classes? Trying to max those DL points...

**Comment by Hectoronian** [comment]
Hi @SecretJsal there is a current pull request by me, hopefuly they approve for use.

#89 (Add New ATIS Branch)

**Comment by iEatNoodlez** [comment]
> Hi @SecretJsal there is a current pull request by me, hopefuly they approve for use.
> 
> #89 (Add New ATIS Branch)

Merged.
