### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Bbrsyon2** [Clutch152/scripts#90]
I pasted the code in console, but it gave a syntax error "Uncaught SyntaxError: Invalid or unexpected token" and upon removing said token the code still doesn't work. Help would be appreciated, thank you

**Comment by Fireguy8** [comment]
Same here

**Comment by vLevyx** [comment]
Getting the same issue as well.

**Comment by Fireguy8** [comment]
Trying to do this on a Mac not sure if that has anything to do with it but I wouldn’t think so

**Comment by v0rl0x** [comment]
function findAPI(win) {
    var attempts = 0;
    var maxAttempts = 500;
    while ((typeof(win.API_1484_11) == 'undefined') && win.parent && win != win.parent && attempts < maxAttempts) {
        win = win.parent;
        attempts++;
    }
    return win.API_1484_11;
}\

remove the \ and it will work, might of been a typo on the update

**Comment by Bbrsyon2** [comment]
i tried that already, its still not working, it just repeats the code back to me

**Comment by Fireguy8** [comment]
Same here thought I was the only one

**Comment by iEatNoodlez** [comment]
Fixed
