### ISSUE TITLE
Improper updated code on JKO @ owner of repo

### ISSUE THREAD

**Issue by v0rl0x** [Clutch152/scripts#91]
function findAPI(win) {
    var attempts = 0;
    var maxAttempts = 500;
    while ((typeof(win.API_1484_11) == 'undefined') && win.parent && win != win.parent && attempts < maxAttempts) {
        win = win.parent;
        attempts++;
    }
    return win.API_1484_11;
}\

you added an extra \ which is causing issues amongst people

**Comment by iEatNoodlez** [comment]
Fixed
