### ISSUE TITLE
Correct syntax issue (READ THIS TO FIX)

### ISSUE THREAD

**Issue by v0rl0x** [Clutch152/scripts#92]
\ remove the slash on the first function

function findAPI(win) {
    var attempts = 0;
    var maxAttempts = 500;
    while ((typeof(win.API_1484_11) == 'undefined') && win.parent && win != win.parent && attempts < maxAttempts) {
        win = win.parent;
        attempts++;
    }
    return win.API_1484_11;
}\

**Comment by Fireguy8** [comment]
This is the correct code?

**Comment by Fireguy8** [comment]
Or could you post the entire correct code?

**Comment by Fireguy8** [comment]
I got it to work but now it’s giving me another code and still not executing

**Comment by uhrdead02** [comment]
the old code still works


API_1484_11.SetValue('cmi.completion_status','completed');if (document.getElementsByName("courseheader").item(0).contentDocument.getElementById("c")){document.getElementsByName("courseheader").item(0).contentDocument.getElementById("c").submit()};

**Comment by iEatNoodlez** [comment]
Fixed
